# Generated by Django 6.0.6 on 2026-06-27 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('procesado', 'Procesado'), ('abandonado', 'Abandonado')], default='activo', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrito_compras',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, default='', max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes_perfil',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id_item', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_moto', models.IntegerField(blank=True, null=True)),
                ('id_repuesto', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='motoshop.carritocompras')),
            ],
            options={
                'db_table': 'items_carrito',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('id_carrito', models.ForeignKey(blank=True, db_column='id_carrito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='motoshop.carritocompras')),
                ('id_usuario_cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='pendiente', max_length=30)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='motoshop.pedido')),
                ('id_usuario_cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_vendedor', models.ForeignKey(db_column='id_usuario_vendedor', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id_financiamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad_financiera', models.CharField(max_length=100)),
                ('monto_financiado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=30)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='financiamientos', to='motoshop.venta')),
            ],
            options={
                'db_table': 'financiamientos',
            },
        ),
    ]
