# Generated by Django 6.0.6 on 2026-06-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tiempo_estimado_minutos', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('kilometraje_actual', models.PositiveIntegerField()),
                ('diagnostico_inicial', models.TextField(blank=True, null=True)),
                ('costo_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('moto', models.ForeignKey(db_column='id_moto', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='motoshop.moto')),
                ('usuario_cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='motoshop.servicio')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Recibida', 'Recibida'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=30)),
                ('moto', models.ForeignKey(blank=True, db_column='id_moto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='motoshop.moto')),
                ('repuesto', models.ForeignKey(blank=True, db_column='id_repuesto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='motoshop.repuesto')),
                ('proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='motoshop.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoMantenimiento',
            fields=[
                ('id_repuesto_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='motoshop.mantenimiento')),
                ('repuesto', models.ForeignKey(db_column='id_repuesto', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='motoshop.repuesto')),
            ],
            options={
                'verbose_name': 'Repuesto de mantenimiento',
                'verbose_name_plural': 'Repuestos de mantenimiento',
                'db_table': 'repuestos_mantenimiento',
            },
        ),
    ]
