# Generated by Django 6.0.6 on 2026-06-27 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0002_proveedor_servicio_mantenimiento_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='solicitada', max_length=30)),
                ('monto_devolucion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='motoshop.venta')),
            ],
            options={
                'db_table': 'devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVenta',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('contrato', 'Contrato'), ('factura', 'Factura'), ('soat', 'SOAT'), ('garantia', 'Garantía'), ('traspaso', 'Traspaso'), ('otro', 'Otro')], max_length=50)),
                ('archivo_url', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='motoshop.venta')),
            ],
            options={
                'db_table': 'documentos_venta',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='motoshop.venta')),
            ],
            options={
                'db_table': 'facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id_garantia', models.AutoField(primary_key=True, serialize=False)),
                ('id_moto', models.IntegerField()),
                ('meses_garantia', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='activa', max_length=30)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='motoshop.venta')),
            ],
            options={
                'db_table': 'garantias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoVenta',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='motoshop.venta')),
            ],
            options={
                'db_table': 'historial_estado_venta',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=30)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, default='', max_length=150)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='motoshop.venta')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id_seguro', models.AutoField(primary_key=True, serialize=False)),
                ('aseguradora', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=100, unique=True)),
                ('tipo_cobertura', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=30)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.PROTECT, related_name='seguros', to='motoshop.venta')),
            ],
            options={
                'db_table': 'seguros',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
