# Generated by Django 6.0.6 on 2026-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0003_devolucion_documentoventa_factura_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteperfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos/'),
        ),
    ]
