# Generated by Django 6.0.6 on 2026-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0007_financiamiento_unique_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoventa',
            name='archivo_url_legacy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
