name: Deploy MotoShop API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /opt/motoshop-api
            git pull origin main
            source .venv/bin/activate
            pip install uv
            uv pip install -r pyproject.toml
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            
